// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorServerAppDB.Data.BlazorServerApp
{
    public partial class AllThemesTable
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public int? ThemeId { get; set; }
        public int? MessageId { get; set; }
    }
}