// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorServerAppDB.Data.BlazorServerApp
{
    public partial class CategoryTable
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public string CategoryName { get; set; }
        public string UserName { get; set; }
    }
}